import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { writeFileSync, mkdtempSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { checkText, checkArgs, compileRules, formatReason } from "./lib/voice-rules.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const gate = join(here, "voice-gate.mjs");

const ids = (findings) => findings.map((f) => f.id);

test("hard: authorship phrases", () => {
  assert.deepEqual(ids(checkText("Описание сгенерировано автоматически")), ["ai-authorship"]);
  assert.deepEqual(ids(checkText("Draft generated by Claude")).sort(), ["ai-authorship", "ai-mention"]);
  assert.deepEqual(ids(checkText("Сделал с помощью ИИ")).sort(), ["ai-authorship", "ai-mention"]);
  assert.equal(checkText("Сгенерировать отчёт по кнопке").length, 0, "verb about the product, not authorship");
});

test("soft: bare AI mentions, product names included", () => {
  assert.deepEqual(ids(checkText("Подключить плагин к Claude")), ["ai-mention"]);
  assert.equal(checkText("OpenAI-совместимый эндпоинт").length, 0, "inside a word");
  assert.equal(checkText("Поле AIM в форме").length, 0);
});

test("soft: heading labels", () => {
  assert.deepEqual(ids(checkText("Контекст: у нас падает логин\nЗадача: починить")), ["heading-label", "heading-label"]);
  assert.deepEqual(ids(checkText("**Acceptance criteria:** works")), ["heading-label"]);
  assert.equal(checkText("Контекст задачи такой: логин падает").length, 0);
});

test("soft: emoji, bureaucratese, as-a-user, bullet wall", () => {
  assert.deepEqual(ids(checkText("Готово ✅")), ["emoji"]);
  assert.deepEqual(ids(checkText("В рамках данной задачи необходимо обеспечить")), ["bureaucratese", "bureaucratese"]);
  assert.deepEqual(ids(checkText("Как менеджер, я хочу видеть отчёт")), ["as-a-user"]);
  assert.equal(checkText("Как договаривались, я хочу закрыть это до пятницы").length, 1, "false positive accepted: comma after role-like phrase");
  const wall = Array.from({ length: 6 }, (_, i) => `- пункт ${i}`).join("\n");
  assert.deepEqual(ids(checkText(wall)), ["bullet-wall"]);
  assert.equal(checkText(wall.split("\n").slice(0, 5).join("\n")).length, 0);
});

test("checkArgs walks top-level fields and items[]", () => {
  const findings = checkArgs({
    subject: "Готово ✅",
    description: "обычный текст",
    items: [{ subject: "ok" }, { description: "Контекст: x" }],
    file_path: "Контекст: not a text field",
  });
  assert.deepEqual(findings.map((f) => [f.field, f.id]), [["subject", "emoji"], ["items[1].description", "heading-label"]]);
});

test("checkArgs tolerates junk", () => {
  assert.deepEqual(checkArgs(null), []);
  assert.deepEqual(checkArgs("string"), []);
  assert.deepEqual(checkArgs({ items: "not an array", subject: 5 }), []);
});

test("quotes are trimmed to 60 chars and formatReason lists them", () => {
  const long = "Контекст: " + "x".repeat(200);
  const [f] = checkText(long);
  assert.ok(f.quote.length <= 60);
  assert.match(formatReason([f]), /рубрика-заголовок/);
});

test("compileRules rejects a broken pattern loudly", () => {
  assert.throws(() => compileRules({ fields: [], hard: [{ id: "x", reason: "x", pattern: "(", flags: "u" }], soft: [] }), /rule "x"/);
});

function runHook(input) {
  return spawnSync(process.execPath, [gate], { input, encoding: "utf8" });
}

test("hook: clean input prints nothing and exits 0", () => {
  const r = runHook(JSON.stringify({ tool_name: "t", tool_input: { subject: "Починил логин" } }));
  assert.equal(r.status, 0);
  assert.equal(r.stdout, "");
});

test("hook: soft findings ask", () => {
  const r = runHook(JSON.stringify({ tool_name: "t", tool_input: { description: "Контекст: x" } }));
  assert.equal(r.status, 0);
  const out = JSON.parse(r.stdout);
  assert.equal(out.hookSpecificOutput.hookEventName, "PreToolUse");
  assert.equal(out.hookSpecificOutput.permissionDecision, "ask");
  assert.match(out.hookSpecificOutput.permissionDecisionReason, /рубрика/);
});

test("hook: hard findings deny", () => {
  const r = runHook(JSON.stringify({ tool_name: "t", tool_input: { comment: "Текст сгенерирован" } }));
  const out = JSON.parse(r.stdout);
  assert.equal(out.hookSpecificOutput.permissionDecision, "deny");
});

test("hook: junk stdin exits 0 silently", () => {
  for (const input of ["", "{not json", "[]", JSON.stringify({ tool_input: null })]) {
    const r = runHook(input);
    assert.equal(r.status, 0, input);
    assert.equal(r.stdout, "", input);
  }
});

test("cli: --file reports and exits 0/1/2", () => {
  const dir = mkdtempSync(join(tmpdir(), "voice-"));
  const clean = join(dir, "clean.md"); writeFileSync(clean, "Починил логин, проверил на стенде.");
  const soft = join(dir, "soft.md"); writeFileSync(soft, "Контекст: логин");
  const hard = join(dir, "hard.md"); writeFileSync(hard, "Черновик сгенерирован");
  assert.equal(spawnSync(process.execPath, [gate, "--file", clean], { encoding: "utf8" }).status, 0);
  const s = spawnSync(process.execPath, [gate, "--file", soft], { encoding: "utf8" });
  assert.equal(s.status, 1); assert.match(s.stdout, /рубрика/);
  assert.equal(spawnSync(process.execPath, [gate, "--file", hard], { encoding: "utf8" }).status, 2);
});
